Cadastro de Autor Concluido
jonilsonds9/e-digi-java pull request #1
Opened 2020-07-22 17:56 UTC by jonilsonds9

2020-07-22 18:50 UTC, wandersonmaceds requested changes

2020-07-22 18:50 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +        }
Aqui alguma coleção diferente das listas poderia te ajudar garantindo que nenhum elemento repetido pode entrar na lista e de quebra te livrar desse contains.

2020-07-22 18:50 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/model/Author.java
> +    public void setName(String name) {
poderia ser privado, já que não tem nenhuma regra explícita que diga ser possível o autor alterar seus dados

2020-07-22 18:50 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/model/Author.java
> +    }
Você não está usando nenhuma estrutura de dados que se baseia no uso de hashses, então por que existe o hashcode aqui?

2020-07-23 13:05 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/model/Author.java
> +    }
Agora com o HashSet preciso, então deixei.

2020-07-23 13:05 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/model/Author.java
> +    public void setName(String name) {
Verdade.

2020-07-23 13:05 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +        }
É verdade, me passou pelo sentido, usando o HashSet isso é resolvido, ainda continuo utilizando o if apenas para exibir a mensagem se o author já tiver sido cadastrado.

2020-07-23 16:52 UTC, wandersonmaceds approved these changes
Boa!

2020-07-24 13:45 UTC, merged