Visualizando um livro concluído
jonilsonds9/e-digi-java pull request #4
Opened 2020-08-10 22:31 UTC by jonilsonds9

2020-08-11 13:17 UTC, wandersonmaceds requested changes

2020-08-11 13:17 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +        });
Funciona, mas acredito que usando a api de streams do Java 8, você consiga fazer um código menos imperativo.

2020-08-11 13:17 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +        System.out.println("Autor: " + book.getAuthor().getName() + "\nLivro: " + book.getTitle() + "\nCadastrado em: " + book.getCreatedAt() + "\n");
Aqui você tá sempre pedindo informações do livro para printar, no tell don't ask, você inverte isso, algo parecido com o toString seria melhor, não faria você precisar de todos esses getters

2020-08-11 13:17 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/test/SearchBooksTest.java
> +        try {
esse teste lança a exception e o teste que não lança, fica onde?

2020-08-12 17:45 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +        });
É verdade, quando mandei o PR foi que me atentei a isso.

2020-08-12 17:46 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +        System.out.println("Autor: " + book.getAuthor().getName() + "\nLivro: " + book.getTitle() + "\nCadastrado em: " + book.getCreatedAt() + "\n");
Acho que entendi a ideia, no caso preciso criar um outro método que já print tudo o que é necessário. Porém nesse caso não pode ser o toString porque ele já é usado para imprimir tudo do Book, posso colocar por exemplo um método `infoBookToString()` para mostrar isso, então não preciso usar os getters.

2020-08-12 17:46 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/test/SearchBooksTest.java
> +        try {
Essa parte eu não entendi muito bem, porque eu usei o try catch apenas para mostrar caso tenha algum erro em algum outro lugar, porque não é para lançar uma exception se algo der errado para o usuário saber qual foi o problema?

2020-08-13 11:38 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/test/SearchBooksTest.java
> +        try {
Sim, mas você não testa apenas o que dá erro, você também precisa garantir que o que não dá erro, também funciona.

2020-08-17 14:25 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/test/SearchBooksTest.java
> +        try {
Eu acho que entendi, dá uma olhada nesse último commit que eu mandei.

2020-08-17 17:12 UTC, wandersonmaceds approved these changes
Acho que tá ok, mas você não precisa dos prints, remove por favor

2020-08-18 17:02 UTC, merged