Garantindo que o sistema funciona com feedbacks
jonilsonds9/e-digi-java pull request #6
Opened 2020-09-01 20:29 UTC by jonilsonds9

2020-09-02 13:39 UTC, wandersonmaceds requested changes
Acho que um questão passou por todos os seus testes.

2020-09-02 13:39 UTC, wandersonmaceds commented on test/br/com/jonilson/edigi/AuthorTest.java
> +        assertEquals(author.getEmail(), authorDao.list().iterator().next().getEmail());
- Aqui você poderia recuperar o autor da lista e usar o equals do autor ou mesmo usar o contains da própria lista.
- Você está usando o set, o add tem um retorno boleano, então você poderia fazer uso desse boleano pra não precisar do list e size.

2020-09-02 13:39 UTC, wandersonmaceds commented on test/br/com/jonilson/edigi/AuthorTest.java
> +    }
Acho que estes 3 testes poderiam ser um só, com os vários asserts dentro, todos eles validam a regra de que um autor não pode ser criado com um estado inválido. (Aqui é só pitaco, pode deixar como está).

2020-09-02 13:39 UTC, wandersonmaceds commented on test/br/com/jonilson/edigi/CategoryTest.java
> +        assertEquals(category.getName(), categoryDao.list().iterator().next().getName());
Mesma coisa do Autor.

2020-09-03 15:27 UTC, jonilsonds9 commented on test/br/com/jonilson/edigi/AuthorTest.java
> +        assertEquals(author.getEmail(), authorDao.list().iterator().next().getEmail());
Verdade, fica bem menos código também!

2020-09-03 15:27 UTC, jonilsonds9 commented on test/br/com/jonilson/edigi/AuthorTest.java
> +    }
Faz sentido realmente, porém no teste de `books` acho que não faz tanto sentido, porque são muitos e ficaria um teste gigantesco, então vou deixar separado mesmo.

2020-09-04 17:53 UTC, wandersonmaceds approved these changes

2020-09-07 16:17 UTC, merged