Trabalhando com banco e testes de integração
jonilsonds9/e-digi-java pull request #7
Opened 2020-09-14 19:02 UTC by jonilsonds9

2020-09-16 13:29 UTC, wandersonmaceds requested changes
Acho que você não precisa separar em classes diferentes seus testes de unidade e de integração.

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
>              throw new IllegalArgumentException("Esse email já está cadastrado!");
Por que IllegalArgument?

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +            statement.setObject(3, author.getCreatedAt());
Aqui poderia ser o timestamp, outra coisa é que você poderia deixar com que o banco gerasse esse dado e apenas preenchesse ele quando o insert executasse (é comum que o banco gere esse dado).

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +            throw new IllegalArgumentException(e);
Por que a SQL Exception foi convertida em IllegalArgument?

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +            throw new IllegalArgumentException(e);
Mesma questão da conversão aqui... Por que?

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +                    author.setCreatedAt(rst.getTimestamp(4).toLocalDateTime());
Ao invés de set, set set, você poderia criar um construtor novo que receba todos os dados de uma vez e use os sets internos.

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +            throw new IllegalArgumentException(e);
??

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +        String query = "SELECT * FROM books";
Aqui você conseguiu evitar o N+1 das queries, embora eu não sei o quão bom é fazer o list de duas outras entidades dentro do list do livro. Outro ponto é: se você recebeu a connection como parametro, por que não receber o list dos autores e das categorias diretamente? E por que não talvez receber os daos por paramentro ao invés de dar new dentro da classe?

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +            throw new IllegalArgumentException(e);
??

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
>      public List<Book> searchBooks(String title) {
Legal, porém fica o questionamento, por que um select do banco cria um Set, mas um filter de um Set se transforma em um List?

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/CategoryDao.java
> +            statement.setObject(2, category.getCreatedAt());
E o timestamp?

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/CategoryDao.java
> +            throw new IllegalArgumentException(e);
??

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/CategoryDao.java
> +            throw new IllegalArgumentException(e);
]]

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/factory/ConnectionFactory.java
> +public class ConnectionFactory {
Se você de alguma forma está controlando o estado da conexão (abrindo e fechando)  aqui, por que fazer isso com métodos estáticos, que vão contra o gestão do estado de objetos?

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/model/Author.java
> +    }
Aqui eu posso roubar no jogo e criar um autor com uma data futura do que ele realmente foi criado, certo?

2020-09-16 13:29 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/model/Category.java
> +    }
data futura

2020-09-19 14:56 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +                    author.setCreatedAt(rst.getTimestamp(4).toLocalDateTime());
Certo, porém eu vou esbarrar na questão de imutabilidade no teste, eu sou fazer algo como:
```
authorDao.add(author);
```
E no DAO:
```
author = new Author(<id, nome, email, data>);
```
Porém no teste vai continuar a referencia para o objeto sem Id, ai não consigo usar no livro ou em outros lugares.
Como resolver isso?

2020-09-19 14:57 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
>              throw new IllegalArgumentException("Esse email já está cadastrado!");
Fiquei na dúvida sobre qual a melhor Exception usar nesse caso. Alguma alternativa melhor nesse caso?

2020-09-19 14:58 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +            statement.setObject(3, author.getCreatedAt());
Isso é facil, porém esbarro na questão da imutabilidade do objeto no teste e não consigo prosseguir.

2020-09-19 15:43 UTC, jonilsonds9 commented
Sobre não precisar separar em classes diferentes os testes de unidade e de integração, onde vi sempre são separados, principalmente porque mais a frente podem vir a serem executar por ferramentas de integração, como Jenkins por exemplo, então como seria isso? Pode dar um exemplo ou algum material a respeito?

2020-09-19 15:45 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +            statement.setObject(3, author.getCreatedAt());
A questão é que mesmo usando um novo construtor não vou conseguir acessar essa nova instancia do objeto no teste, a não ser que eu retorne um novo Author, porém isso é correto? Um método para adicionar retornar uma nova instância?

2020-09-19 16:58 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
>              throw new IllegalArgumentException("Esse email já está cadastrado!");
Aqui você pode trocar a mensagem dizendo que o autor já existe (já que essa é a regra do negócio) e no caso, vai ser uma RuntimeException, a ideia é que o objeto é um autor válido, por isso não casa bem com a ideia de IllegalArgument

2020-09-19 17:00 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +            statement.setObject(3, author.getCreatedAt());
Isso depende bastante, retornar um novo autor fará sentido se pensar em algo funcional, mas sim, pode ser só o setId, sem problema. Não entendi a questão da imutabilidade do objeto, quer falar mais sobre isso?

2020-09-19 17:08 UTC, wandersonmaceds reviewed
Os testes serem executados por ferramentas de integração não tem relação com como você estrutura seus testes, mas deixe assim, acho que é uma boa reflexão para meu eu do futuro :p

2020-09-19 17:08 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +                    author.setCreatedAt(rst.getTimestamp(4).toLocalDateTime());
Aqui não tem problema nenhum, no Java você pode ter sobrecarga de construtores, e pensando nisso, você pode ter um construtor que recebe um id e outro que não recebe. Neste caso em específico, você sempre vai pegar todos os campos no banco, então faz sentido ter um construtor que recebe tudo de uma vez.

2020-09-20 15:33 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +                    author.setCreatedAt(rst.getTimestamp(4).toLocalDateTime());
Sim, também acho que faz sentido usar a sobrecarga de construtor, porém no teste eu crio um objeto Author:
```
@Test
public void shouldRegisterAuthor() {
    AuthorDao authorDao = new AuthorDao(this.connection);

    Author author = new Author("ana", "ana@gmail.com");

    authorDao.add(author);

    assertTrue(authorDao.list().contains(author));
}
```
E passo esse objeto para o DAO na linha:
```
authorDao.add(author);
```
Porém lá no DAO eu preciso usar a sobrecarga de construtores para criar um novo objeto e passar esse objeto para a variável `author` que foi enviada no trecho de código acima:
```
while (rst.next()) {
    author = new Author(
        rst.getInt(1),
        rst.getString(2),
        rst.getString(3),
        rst.getTimestamp(4).toLocalDateTime());
}
```
Porém se eu voltar no teste e fizer um `getId()` eu recebo um NullPointerException:
```
authorDao.add(author);

author.getId();
```
E isso acontece pela questão da imutabilidade do objeto, se eu apesar fizer um `setId` e um `setCreatedAt()` ai sim tudo bem porque vai ser o mesmo **objeto** porém como o Id e a Data, então é esse o problema, por isso que não estou conseguindo usar a sobrecarga de construtores, ai usei os setters.

2020-09-20 15:33 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +            statement.setObject(3, author.getCreatedAt());
Fiz um comentário abaixo explicando minha dificuldade, dá uma olhada e vê se entende o que estou tentando falar.

2020-09-26 11:33 UTC, wandersonmaceds requested changes

2020-09-26 11:33 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +                            .filter(a -> a.getId() == author.getId()).findFirst().get().getCreatedAt());
Não entendi, por que precisa disso? se você pode no getGeneratedKeys fazer o set do createdAt diretamente? o getGeneratedKeys não devolve só o ID não.

2020-09-26 11:33 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +                            .filter(b -> b.getId() == book.getId()).findFirst().get().getCreatedAt());
getGeneratedKeys()

2020-09-26 11:33 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +                            .filter(b -> b.getId() == book.getId()).findFirst().get().getCreatedAt());
https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#getGeneratedKeys--

2020-09-27 13:11 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/AuthorDao.java
> +                            .filter(a -> a.getId() == author.getId()).findFirst().get().getCreatedAt());
Pensei muito nessa parte do código, e coloquei mesmo achando estranho e feio essa parte, porém só fiz isso porque não encontrei outra forma, porque o `getGeneratedKeys()` só retorna o ID, quando eu tento pegar outra coluna ele dá erro, por exemplo, se eu colocar o código dessa forma:
```
ResultSet rst = statement.getGeneratedKeys();
    if (rst.next()) {
        System.out.println(rst.getString(2));
        System.out.println(rst.getTimestamp(4));

        author.setId(rst.getInt(1));
```
Ele retorna o erro:
```
java.lang.RuntimeException: java.sql.SQLException: Column Index out of range, 2 > 1. 

at br.com.jonilson.edigi.dao.AuthorDao.add(AuthorDao.java:49)
```
Ele só tem 1 index, então só tem o ID. Como fazer isso então? Tem algum exemplo? Uma forma melhor? Eu sei que essa parte não ficou tão legal, mas bati muito nesse erro e então fiz dessa forma, para aqui na revisão ver uma outra forma.

2020-09-27 13:16 UTC, jonilsonds9 commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +                            .filter(b -> b.getId() == book.getId()).findFirst().get().getCreatedAt());
O mesmo problema anterior, eu não encontrei outra alternativa, o `getGeneratedKeys()` retorna apenas as chaves, então como eu pego a data para atribuir ao atributo `created_at` do Objeto `Author`? Não consegui ver uma outra maneira, a **não ser fazendo outro SELECT no banco com essa chave retornado**, então achei mais fácil pegar todos os dados usando o método `list` do mesmo DAO e então fazer esse filtro para pegar o Objeto pronto e então pegar o `created_at` gerado pelo banco e colocar no objeto `Author` que estou recebendo do teste.

2020-09-29 10:52 UTC, wandersonmaceds commented on src/br/com/jonilson/edigi/dao/BookDao.java
> +                            .filter(b -> b.getId() == book.getId()).findFirst().get().getCreatedAt());
Mesmo que o getGeneratedKeys não dê pra você o createdAt, a solução atual é ruim por que seu list traz tudo para pegar apenas um resultado que você sabe qual é (tem um id ali) então por que você carregaria 20k de registros (exemplo) para filtrar apenas um em memória? Não seria mais prático fazer um select por ai e pegar apenas o dado que quer?

2020-09-30 17:09 UTC, wandersonmaceds approved these changes

2020-09-30 20:49 UTC, merged